const authorisedRoles = {
    "/api/patient/:patientId": ["patient", "admin"],
    "/api/patients/": ["patient", "admin"],
    "/api/appointments": ["patient"],
    "/api/appointments/patient/:patientId": ["patient"],
    "/api/appointments/:appointmentId": ["patient"],
    "/api/patient/makePayment": ["patient"],
    "/api/mail/paymentConfirmation": ["patient"],
    "/api/patients/unapproved": ["admin"],
    "/api/patient/:patientId/paymentMethods": ["patient"],
    "/api/patient/:patientId/paymentMethods/:methodId": ["patient"],
    "/api/chatbot/sendMessage": ["patient"],
    "/api/chatbot/history/:patientId": ["patient"],
    "/api/patient/:patientId/digitalWallet": ["patient"],
    "/api/patient/:patientId/digitalWalletHistory": ["patient"],

    "/api/drugRequests/": ["company"],
    "/api/drugRequest/:appointmentId/:drugName": ["company"],
    "/api/drugRequest/contribute/:appointmentId/:drugName": ["company"],
    "/api/drugRequest/drugContribution": ["company"],
    "/api/drugContributionOrders/:companyId": ["company"],
    "/api/drugContributionOrders/:appointmentId/:drugName": ["company"],
    "/api/drugContributionOrders/:appointmentId/:drugName": ["company"],
    "/api/drugInventoryRecord/:drugRecordId/:drugQuantity": ["company"],
    "/api/companyDrugInventory/": ["company"],
    "/api/companyDrugInventory/:companyId/:drugName": ["company"],
    "/api/companyDrugInventory/addDrug": ["company"],
    "/api/companyDrugInventory/:companyId/:drugName/:drugQuantity": ["company"],
    "/api/inventoryRecord/:companyId": ["company"],
    "/api/inventoryRecord/:drugRecordId": ["company"],
    "/api/inventoryRecord/:drugRecordId": ["company"],
};

module.exports = authorisedRoles;